version: 0.2
# env:
#   parameter-store:
#     REPOSITORY_URI: "BACKEND_REPOSITORY_URI"
#     IMAGE_TAG: "IMAGE_TAG"
#     IMAGE_NAME: "BACKEND_IMAGE_NAME"
#     DOCKERHUB_USER: "DOCKERHUB_USER"
#     DOCKERHUB_PASSWORD: "DOCKERHUB_PASSWORD"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - pwd
      - docker build -f deploy/Dockerfile -t $IMAGE_NAME .
      - docker images
      - docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG ...
      - DOCKER_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $DOCKER_URL

  # pre_build:
  #   commands:
  #     - echo Logging in to Amazon ECR...
  #     - aws --version
  #     - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  #     - echo Logging in to Docker Hub...
  #     - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
  # build:
  #   commands:
  #     - echo Building the Docker image...
  #     - pwd
  #     - docker build -f deploy/Dockerfile -t $IMAGE_NAME .
  #     - docker images
  #     - docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  # post_build:
  #   commands:
  #     - echo Pushing the Docker images...
  #     - docker push $REPOSITORY_URI:$IMAGE_TAG
