version: '3'

services:

# PHP環境
  php:
    container_name: php
    build: ./lib/php
    volumes:
    - ./src:/var/www

# NGINX環境
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./src:/var/www
    - ./lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    - minio

# DB環境
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./lib/mysql/data:/var/lib/mysql
    - ./lib/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./lib/mysql/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - ./lib/phpmyadmin/sessions:/sessions

 #S3環境
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9090:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /usr/bin/minio server /data;
      "
    volumes:
      - ./lib/minio/data:/data
      - ./lib/minio/export:/export
      - ./lib/minio/config:/root/.minio
      - ./lib/minio/policies:/policies

