version: "3.8"
services:
# 作業環境
  workspace:
    build: ./lib/php
    volumes:
      - ./src:/work

# Webサーバー
  web:
    container_name: web-box
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./src:/work
      - ./lib/nginx/web/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

# APIサーバー
  api:
    container_name: api-box
    image: nginx:1.18-alpine
    ports:
      - 10081:80
    volumes:
      - ./src:/work
      - ./lib/nginx/api/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

# mysql
  db:
    image: mysql:5.7
    container_name: db-box
    environment:
      MYSQL_DATABASE: workdb
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./lib/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./lib/mysql/init:/docker-entrypoint-initdb.d
      - ./lib//log:/var/log/mysql
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db-box
    - PMA_USER=phper
    - PMA_PASSWORD=secret
    ports:
    - 8080:80

volumes:
  db-data:
    driver: local
